### ISSUE TITLE
spotless gradle plugin leaks memory (massively)

### ISSUE THREAD

**Issue by lkoe** [diffplug/spotless#1194]
From my preliminary analysis of instabilities in our build environment I suspect that spotless gradle plugin is massively leaking memory in the gradle daemon.

It seems that via `GitAttributesLinieEndings$RelocatablePolicy` the `JVMLocalCache` holds onto complete project references, which cannot be collected by a full gc of the daemon process.

![spotless-leak](https://user-images.githubusercontent.com/2411009/166706641-0267a11c-3d41-4979-a7ec-0950f73c80a6.png)

The image shows a full gc after the build of one of our projects (admittedly one having about 35 subprojects), with spotless applied vs. spotless not applied.
Also shown a GC root analysis on the daemon heap dump, showing the suspected offender.

The expectation would be that spotless only caches calculated values (and using weak cache values that could be collected if need be).

Using spotless-gradle-plugin 6.5.2

```
Gradle 7.3.3
------------------------------------------------------------

Build time:   2021-12-22 12:37:54 UTC
Revision:     6f556c80f945dc54b50e0be633da6c62dbe8dc71

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.12 (Amazon.com Inc. 11.0.12+7-LTS)
OS:           Windows 10 10.0 amd64
```

**Comment by nedtwigg** [comment]
Thanks for the bug report, I should have a fix published by tomorrow.

**Comment by lkoe** [comment]
Thanks, much appreciated.
I tried to work around by setting `spotless.lineEndings=PLATFORM_SPECIFIC` (from memory).
This "solved" this particular occurrence, but revealed more offenders. Couldn't finish this today, but will attach more info tommorow morning (CEST).

**Comment by lkoe** [comment]
Ok, I after dealing with lineEndings as above, the next issue seems to be [`GradlePrivsioner#forConfigurationContainer` ](https://github.com/diffplug/spotless/blob/main/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/GradleProvisioner.java#L111), where project related references are "backed" into a lambda, which cannot be collected:

![spotless-leak2](https://user-images.githubusercontent.com/2411009/166866930-3646cba2-e4ce-406a-a7fe-b1a0aa36da95.png)

This affects `RemoveUnusedImportsStep`, `GsonStep` and `EclipseBasedStepBuilder`.

After disabling those from my spotless config, another issue is shown with `LicenseHeaderStep`, which is potentially induced by https://github.com/diffplug/spotless/blob/main/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java#L505 (again a lamda using a project related ref?)

![spotless-leak3](https://user-images.githubusercontent.com/2411009/166867806-db2beb50-c7ae-444c-9da0-a3213d26aea7.png)

After disabling the `LicenseHeaderStep` from our config, full GC could finally reclaim the memory in the daemon process 😅 

So it appears the issue is a bit more wide spread than initially suggested, pointing to a bit of a conceptual "tug-of-war" between caching and lazyness.

**Comment by lkoe** [comment]
Thanks for the fix, I tested it.
It works, *if* all projects in a build are successfull.

Unfortunately, if one of the projects in a multi-build fails (e.g. during `spotlessCheck`), `RelocatablePolicy#calculateState` is never called for the remaining projects, so in this case the leak remains.
I haven't checked if the other fix locations would trigger a similar problem

**Comment by nedtwigg** [comment]
Thanks for testing this, the commit above makes sure that `calculateState` is always called before a value makes it into the daemon-level cache.

**Comment by lkoe** [comment]
Thanks, unfortunately there seems to be still a reference that slips by in the "broken build" scenario, coming from `GradleProvisioner`. 

![spotless-leak4](https://user-images.githubusercontent.com/2411009/167573607-3c3e2f51-89b1-497a-aa22-9cbae42aaac7.png)

JVisualVM seems to pick one of the uncollectable reference chains when displaying GC roots, so they were hidden by the earlier issue. Sorry for the "drop by drop" reporting...

**Comment by nedtwigg** [comment]
> Sorry for the "drop by drop" reporting...

Are you kidding!? Thanks for sticking with this! I'm giving drop-by-drop fixes, and I think our incremental approach is the fastest way we could do this. The code design has definitely picked up some warts as the Gradle model has changed, but the lazyness is still helpful to how Spotless is used in Maven builds, so I think the little kludges we've had to accept are our best option.

**Comment by nedtwigg** [comment]
I think this is fixed in `plugin-gradle 6.6.0`. Can you confirm before I close this?

**Comment by lkoe** [comment]
Thanks again, I tested the 6.6.0 release but I still see the leak via the same reference chain as above (https://github.com/diffplug/spotless/issues/1194#issuecomment-1122034178)

As fair as I understand the code, the latest changes do not yet apply there, bc. `RemoveUnusedImportsStep` and `GsonStep` (and possible others) are creating `FormatterStepImpl` via https://github.com/diffplug/spotless/blob/49099f3ae502ecdbd19381da0990cf027d4c8707/lib/src/main/java/com/diffplug/spotless/java/RemoveUnusedImportsStep.java#L32 and https://github.com/diffplug/spotless/blob/main/lib/src/main/java/com/diffplug/spotless/FormatterStep.java#L107 which in itself is not yet a `DelegateFormatterStep` as per the lastest commit.

**Comment by lkoe** [comment]
Pls disregard my earlier analysis attempt - I see that `FormatterStepImpl` already extends `LazyForwardingEquality`, but it appears it is not working in all cases.

**Comment by lkoe** [comment]
Ok, did some more debugging and it appears that `value` here (https://github.com/diffplug/spotless/blob/main/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/JvmLocalCache.java#L57) can be a collection of `FormatterStepImpl` in which case the "unlazying" doesn't happen

**Comment by lkoe** [comment]
ok, after some local patching it seems that losing the `instanceof` and the cast to `LazyForwardingEquality` here (https://github.com/diffplug/spotless/blob/main/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/JvmLocalCache.java#L57) does indeed fix all remaining leaks, as `LazyForwardingEquality#unlazy` already takes care of all the corner cases (delegates, collections).

**Comment by lkoe** [comment]
Hmm, while the "unlazying" cleans up the memory leaks, I have now a new problem at hand to deal with.

We wrap spotless-gradle (among others) in our own inhouse convention plugin, which configures all of our projects consistently.
In order to achieve this, our plugin "smuggles" a custom task before the spotless tasks in order to create the necessary file structure in the project dynamically. These files are located within our plugin and are essentielly copied from the plugin classpath into the projects.

However, now with the fixes above in place - spotless tries to resolve all its configuration file (headers, import order...) earlier than before, even before our custom task had a chance to export all those files into the project.

The stacktrace looks like this:

```
com.diffplug.spotless.ThrowingEx$WrappedAsRuntimeException: java.nio.file.NoSuchFileException: <path-tp-project>\build\formatter\properties\licence.header
        at com.diffplug.spotless.ThrowingEx.asRuntime(ThrowingEx.java:92)
        at com.diffplug.spotless.LazyForwardingEquality.state(LazyForwardingEquality.java:58)
        at com.diffplug.spotless.LazyForwardingEquality.unlazy(LazyForwardingEquality.java:118)
        at com.diffplug.spotless.LazyForwardingEquality.unlazy(LazyForwardingEquality.java:124)
        at com.diffplug.gradle.spotless.JvmLocalCache$LiveCacheKeyImpl.set(JvmLocalCache.java:61)
        at com.diffplug.gradle.spotless.SpotlessTask.setSteps(SpotlessTask.java:168)
        at com.diffplug.gradle.spotless.SpotlessTaskImpl_Decorated.setSteps(Unknown Source)
        at com.diffplug.gradle.spotless.FormatExtension.setupTask(FormatExtension.java:762)
        at com.diffplug.gradle.spotless.SpotlessExtensionImpl.lambda$createFormatTasks$6(SpotlessExtensionImpl.java:70)
        ...
        at com.sun.proxy.$Proxy56.afterEvaluate(Unknown Source)
```

So it looks like this all happens in `afterEvaluate` now.

This means I could now:
* drop our custom spotless profile export task and invoke its logic during configuration (not ideal)
* ... ?

The ideal thing (in our use case) would be if I could configure the spotless extension directly with classpath resources, eliminating the need to export the spotless profile into each project directory altogether?
What's your take on this?
If you consider this worthwhile I could try to whip up a PR, which at least shows the intention.

**Comment by nedtwigg** [comment]
Yeah, a consequence of fixing the memory leaks is that the `FormatterStep` get configured sooner than they did before, so thanks for posting about that here. I'm going to close this issue because the memory leak is solved, and I'm going to open a new issue about loading resources from the classpath (and other places) and timing issues therein.

**Comment by nedtwigg** [comment]
Here's the issue re: loading resources from the classpath.

- https://github.com/diffplug/spotless/issues/1204

**Comment by lkoe** [comment]
I'm sorry, but would you mind to still apply the final fix (or something similar) suggested here? https://github.com/diffplug/spotless/issues/1194#issuecomment-1123863628

**Comment by lkoe** [comment]
Thank you, fix confirmed - I don't see any leaks anymore 👍

**Comment by ZacSweers** [comment]
I think this issue has regressed in later versions. We are seeing a huge amount of memory being taken by Spotless `JvmLocalCache` in 6.18.0, even when not running spotless itself.

![image](https://user-images.githubusercontent.com/1361086/235282825-6b9d0246-1926-4f07-b01f-53bef78ed05d.png)

**Comment by nedtwigg** [comment]
1. There are a few low-hanging fruit I need to get to which will reduce the scope of our configuration cache workaround
2. From the attached screenshot, I can't see the problem. Earlier in the thread, there are screenshots which show how an unwanted class is being kept by some GC root. In the screenshot above, all I can see is that JvmLocalCache is consuming 1.3 million somethings - bytes? Which seems modest. I'm guessing I'm misreading the screengrab.

Happy to reopen and squash this if you have time to trace GC roots, or if you want to wait for the issues below to close first that works too

- https://github.com/diffplug/spotless/issues/1644
- https://github.com/diffplug/spotless/pull/1096

**Comment by lkoe** [comment]
Hi there, while upgrading to the latest spotless I revisited the issue and indeed it seems to have regressed.

Here are some GC roots holding project references, though I didn't quite wrap my head around whats happening.
Common denominator seems to be `FormatExtension` holding onto a project ref via lamda:

![image](https://github.com/diffplug/spotless/assets/2411009/47c8842b-c5f1-4378-b135-0475cb779fb4)
![image](https://github.com/diffplug/spotless/assets/2411009/afacb21d-d95d-4d4f-9da0-aa9a9b407cb5)
![image](https://github.com/diffplug/spotless/assets/2411009/41a43788-593f-4668-bdc5-0a04e1432c89)

**Comment by lkoe** [comment]
bump

**Comment by denzap** [comment]
Have the same problem
Seems like this is regression bug since `6.21.0`
