### ISSUE TITLE
Formatting Java breaks long literals with underscores

### ISSUE THREAD

**Issue by obecker** [diffplug/spotless#14]
I guess this a bug of the Eclipse formatter used under the hood, nevertheless I'm going to report it here:
My Java source files contain `long` literals like

    long foo = 123_456_789L;

Using `spotlessApply` turns this into the syntactically wrong line

    long foo = 123_456_789 L;

(note the additional space between the digits and the L).

This problem can be fixed by adding the following custom rule

    custom 'long literal fix', { it.replaceAll('([0-9_]+) [Ll]', '$1L') }

However, spotless should work correctly without requiring this tweak.

**Comment by nedtwigg** [comment]
Thanks for reporting this and finding a workaround.  I'll try updating the underlying eclipse to the recently released 4.5.2 and see if that fixed it.  If not, I'll file a bugreport with eclipse.

**Comment by nedtwigg** [comment]
I just released Spotless 1.3.3, which uses Eclipse 4.5.2.  4.5.2 fixes a bunch of bugs, but I didn't see anything about long formatting.

Also, I wasn't able to reproduce your bug.  Why don't you try upgrading to 1.3.3 and lemme know if that fixes it for you.  If it does, then we're all set.  If it doesn't, I'd love a repo on Github that  I could checkout and run spotlessApply that shows the bug.  It could be that it's a combination of formatting longs inside a lambda block, or something like that, which might be why I'm not able to reproduce.

**Comment by obecker** [comment]
Thanks for the upgrade. The problem is still present. I will create an example project as soon as I find the time.

**Comment by nedtwigg** [comment]
Thanks!  Should just need a build.gradle, eclipseformat.xml, and a source file.

**Comment by obecker** [comment]
This is the repo that demonstrates the problem: https://github.com/obecker/spotless-demo

Apparently it is a combination of long values and annotations. There are two classes in the demo project: Example1 produces the wrong formatting, Example2 tries a work-around, which however cannot be formatted at all.

**Comment by nedtwigg** [comment]
Thanks for the test case!  I was able to figure out a couple things:

1. Your formatting file actually has two profiles in it, so it's ambiguous which profile you actually want to use.  I've added a warning to Spotless 1.4.0-SNAPSHOT to let users know that they've got two profiles in their file.  Search `<profile` in your file to see what I mean.
2. The formatting file is requiring source compliance 1.5.  Find/replacing 1.5 with 1.8 seems to fix Example2, but not Example1.
3. If I import your formatting file into Eclipse, it works just fine there.  This means that I don't have a clean bug report to give to the Eclipse formatter team, because it seems to be a Spotless-specific problem.

There's a couple things that might be going on:

1. The Eclipse formatter expects to run in an OSGi container (as it does in the GUI), but has fallbacks in case it isn't (as it does in Spotless).  There might be a behavior change there.
2. The Eclipse GUI might be doing some sanitizing of your eclipseformatter.xml, so that the formatter that ends up getting instantiated is a little different than the one that Spotless is creating.
3. Gradle also has the JDT on its classpath, and it's an old version.  There's some known wonkiness where Gradle's classpath pollutes the compile classpath, and that might be mucking with the jar that Spotless compiles a little bit.

Because this problem reproduces differently in each environment, to really figure this out we'd need expertise with:
- the nitty-gritty of gradle's compilation process
- the JDT formatter
- how the JDT formatter interacts with OSGi
- how the Eclipse GUI instantiates a JDT formatter

Formatting long literals with underscores inside of an annotation is a valid usecase that I'd like to fix, but it's also one hell of a cornercase.  Since it will need such broad and deep expertise to get to the bottom of it, I think it's unlikely to actually get solved anytime soon.  Sorry for the unsatisfactory answer for now, but I'll keep tabs on this in the future as Gradle and Eclipse keep improving.

**Comment by nedtwigg** [comment]
I think this is fixed in 2.0.0.  Reopen if you've still got a problem :+1:
